### ISSUE TITLE
Page Naming for Files is outdated

### ISSUE THREAD

**Issue by rjkohler** [academie-de-espee/academie-de-espee.github.io#189]
There are several pages referenced on the front page that, while content is decent, the filenames are not clear and descriptive.

The pages that should be reviewed and corrected as necessary at all link points are as follows (listed under each header):
- General Structural Information: guild
- Masters
  - Roster of Masters: masters
- Provosts
  - What is a Provost?: guidelines
  - Roster of Provosts: provosts
- Free Scholars
  - What is a Free Scholar?: freescholar-2
  - Roster of Free Scholars: fs
- Scholars
  - What is a Scholar?: scholar
  - Roster of Scholars: scholars

**Comment by demoray** [comment]
I suggest making the filenames descriptive beyond "scholar".  something like "scholar-definition", etc

**Comment by demoray** [comment]
OBE
